### ISSUE TITLE
You need to change mod id.

### ISSUE THREAD

**Issue by K0-RR** [williambl/portable-jukebox-fabric#4]
With default mod id you won't get issues reports as users won't know which mod caused the bug. If there is more than one mod in a modpack with the modid not changed Minecraft will not launch.
Users already have problems caused by this -  https://www.reddit.com/r/fabricmc/comments/oequmt/can_i_fix_this_in_any_easy_way_to_edit_the_mod_id/

**Comment by williambl** [comment]
Closed in 16920fa
